// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfdebixaihpnnrjcovyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmZGViaXhhaWhwbm5yamNvdnl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNTQxMzksImV4cCI6MjA1ODkzMDEzOX0.DdOy2ESB32EMc6Wzjm8oN6KL1J3YP6xGiZ-HBgVlLl0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);